email:
  smtp:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    encryption: tls
    from: ${FROM_ADDRESS}

notifications:
  # Service status notifications
  service_down:
    enabled: true
    recipients:
      - ${ADMIN_EMAIL}
    subject: "[ALERT] Service {service} is down"
    
  # Security notifications
  security_alert:
    enabled: true
    recipients:
      - ${ADMIN_EMAIL}
    subject: "[SECURITY] {alert_type} detected"
    
  # Backup notifications
  backup_status:
    enabled: true
    recipients:
      - ${ADMIN_EMAIL}
    subject: "[BACKUP] {status} - {timestamp}"
    
  # System notifications
  system_alert:
    enabled: true
    recipients:
      - ${ADMIN_EMAIL}
    subject: "[SYSTEM] {alert_type} - {message}"

templates:
  service_down: |
    Service {service} is currently down.
    Time: {timestamp}
    Last Status: {last_status}
    Additional Info: {message}
    
  security_alert: |
    Security Alert Detected
    Type: {alert_type}
    Source IP: {source_ip}
    Time: {timestamp}
    Details: {message}
    
  backup_status: |
    Backup Status Report
    Status: {status}
    Time: {timestamp}
    Size: {backup_size}
    Location: {backup_location}
    Details: {message}
    
  system_alert: |
    System Alert
    Type: {alert_type}
    Time: {timestamp}
    Component: {component}
    Message: {message}
    Action Required: {action_required} 