global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: traefik
    static_configs:
      - targets: ['traefik:8082']

  - job_name: plex
    static_configs:
      - targets: ['plex-exporter:9594']
    basic_auth:
      username: prometheus
      password_file: /run/secrets/prometheus_password

  - job_name: sonarr
    static_configs:
      - targets: ['sonarr:8989']
    metrics_path: /metrics

  - job_name: radarr
    static_configs:
      - targets: ['radarr:7878']
    metrics_path: /metrics

  - job_name: lidarr
    static_configs:
      - targets: ['lidarr:8686']
    metrics_path: /metrics

  - job_name: prowlarr
    static_configs:
      - targets: ['prowlarr:9696']
    metrics_path: /metrics

  - job_name: readarr
    static_configs:
      - targets: ['readarr:8787']
    metrics_path: /metrics
