http:
  middlewares:
    secure-headers:
      headers:
        sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
        contentSecurityPolicy: "default-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; connect-src 'self' https:; frame-ancestors 'self'"

    rate-limit:
      rateLimit:
        average: 100
        burst: 50
        period: 1s

    auth-github:
      forwardAuth:
        address: "http://oauth2-proxy:4180"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Auth-Request-Access-Token"
          - "X-Auth-Request-User"
          - "X-Auth-Request-Email"
          - "Authorization"

    chain-secure:
      chain:
        middlewares:
          - secure-headers
          - rate-limit
          - auth-github