http:
  middlewares:
    secure-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
        contentSecurityPolicy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; frame-ancestors 'self'"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Real-IP: "${REMOTE_ADDR}"
        customResponseHeaders:
          Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
          X-Content-Type-Options: "nosniff"
          X-Frame-Options: "SAMEORIGIN"
          X-XSS-Protection: "1; mode=block"
          Referrer-Policy: "strict-origin-when-cross-origin"
          Permissions-Policy: "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()"

    rate-limit:
      rateLimit:
        average: 100
        burst: 50
        period: 1m

    auth-whitelist:
      ipWhiteList:
        sourceRange:
          - "10.10.0.0/16"  # All internal VLANs
          - "202.128.124.242/32"          # Public IP
          fields:
            headers:
              names:
                - "Authorization"
                - "X-Auth-Request-Access-Token"
                - "X-Auth-Request-User"
                - "X-Auth-Request-Email"

    chain-oauth:
      chain:
        middlewares:
          - secure-headers
          - oauth2-headers
          - oauth2-logging
          - rate-limit

    metrics-auth:
      basicAuth:
        users:
          - "admin:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/" # admin:admin

    acme-middleware:
      chain:
        middlewares:
          - secure-headers@file
          - acme-allow@file

    acme-allow:
      ipWhiteList:
        sourceRange:
          - "10.10.0.0/16"  # All internal VLANs
          - "202.128.124.242/32"          # Public IP
          fields:
            headers:
              names:
                - "SAMLRequest"
                - "SAMLResponse"
                - "RelayState"

    chain-saml:
      chain:
        middlewares:
          - secure-headers
          - saml-headers
          - saml-logging
          - rate-limit

