global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: "DEBUG"
  filePath: "/var/log/traefik/traefik.log"
  format: "json"

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: "json"
  bufferingSize: 100
  filters:
    statusCodes:
      - "100-599"
    retryAttempts: true
    minDuration: "10ms"
  fields:
    defaultMode: keep
    names:
      StartUTC: keep
      Duration: keep
      RequestMethod: keep
      RequestPath: keep
      RequestProtocol: keep
      DownstreamStatus: keep
      RouterName: keep
      ClientIP: keep
      ClientHost: keep
      ClientPort: keep
      ClientUsername: keep
      TLSVersion: keep
      TLSCipher: keep
    headers:
      defaultMode: drop
      names:
        Authorization: redact
        X-Auth-Request-Access-Token: redact
        X-Auth-Request-User: keep
        X-Auth-Request-Email: keep
        X-Forwarded-For: keep
        User-Agent: keep
        Referer: keep

api:
  dashboard: true
  insecure: false
  debug: true

providers:
  docker:
    endpoint: "tcp://localhost:2375"
    exposedByDefault: false
    watch: true
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
  metrics:
    address: ":8082"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "admin@sharphorizons.tech"
      storage: "/letsencrypt/acme.json"
      keyType: "EC384"
      httpChallenge:
        entryPoint: "web"

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 0.5
      - 0.8
      - 1.2
      - 2.0
      - 3.0
      - 5.0

ping:
  entryPoint: web

experimental:
  kubernetesGateway: false
