global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  debug: true
  insecure: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    network: proxy
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: "sharphorizons.tech"
            sans:
              - "*.sharphorizons.tech"

  metrics:
    address: ":8082"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "matheusfernal@gmail.com"
      storage: "/letsencrypt/acme.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      keyType: EC384
      httpChallenge:
        entryPoint: web

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

log:
  level: DEBUG
  format: json
  filePath: "/var/log/traefik/traefik.log"

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
  filters:
    statusCodes:
      - "400-499"
      - "500-599"
  fields:
    defaultMode: keep
    headers:
      defaultMode: drop
      names:
        Authorization: redact
        X-Auth-Request-Access-Token: redact
  bufferingSize: 100